### ISSUE TITLE
Make both arguments optional.

### ISSUE THREAD

**Issue by Shaftway** [robwierzbowski/gulp-intermediate#3]
I'd like to make both arguments to gulp-intermediate optional.  I mean, options already is (kind of, but it's first, so it just handles nulls gracefully), but I'd like to make process optional as well.  I have no problem doing the work and submitting a PR for this.

**Comment by robwierzbowski** [comment]
I'm not maintaining this at all anymore. If you're using it I'd be happy to gift it to you and make you a maintainer.

**Comment by hounshell** [comment]
Up to you.  PR request is in, and pretty simple.  Everything is backwards
compatible.

**Comment by elliot-nelson** [comment]
PR merged to master, will be included in next release.
